#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
                    KC_Q,   KC_W,   KC_E,   KC_R,   KC_T,                               KC_Y,   KC_U,   KC_I,   KC_O,   KC_P, 
        KC_TAB,     KC_A,   KC_S,   KC_D,   KC_F,   KC_G,                               KC_H,   KC_J,   KC_K,   KC_L,   KC_SCLN, KC_QUOT, 
        KC_DEL,     KC_Z,   KC_X,   KC_C,   KC_V,   KC_B,   KC_MUTE,        KC_MPLY,    KC_N,   KC_M,  KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, 
                                        KC_LCTL, KC_TRNS, KC_SPC, KC_LALT,        KC_LGUI, KC_ENT, KC_TRNS, KC_BSPC),
    [1] = LAYOUT(
                    KC_Q,   KC_W,   KC_E,   KC_R,   KC_T,                               KC_Y,   KC_U,   KC_I,   KC_O,   KC_P, 
        KC_TAB,     KC_A,   KC_S,   KC_D,   KC_F,   KC_G,                               KC_H,   KC_J,   KC_K,   KC_L,   KC_SCLN, KC_QUOT, 
        KC_DEL,     KC_Z,   KC_X,   KC_C,   KC_V,   KC_B,   KC_MUTE,        KC_MPLY,    KC_N,   KC_M,  KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, 
                                        KC_LCTL, KC_TRNS, KC_SPC, KC_LALT,        KC_LGUI, KC_ENT, KC_TRNS, KC_BSPC),
    
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)


